controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_login:
    path: /login
    controller: App\Controller\ControladorSeguridadController::login

app_logout:
    path: /logout
    controller: App\Controller\ControladorSeguridadController::logout